import { ResearchArea } from "@/types";

export const researchDirectionStatement =
  "Trustworthy generative MLLMs: evidence-grounded calibration and selective abstention under missing, conflicting, or degraded visual evidence.";

export const researchApproachPoints = [
  {
    title: "Open-Weight Generative MLLMs",
    description:
      "Focusing on inspectable, reproducible open-weight multimodal architectures to ensure full visibility into model activations and attention maps.",
  },
  {
    title: "Public Benchmark Datasets",
    description:
      "Utilizing standardized, publicly accessible datasets to guarantee verifiable experimental baselines across visual question answering and document reasoning.",
  },
  {
    title: "Deterministic Evaluation",
    description:
      "Employing structured test fixtures and deterministic metric harnesses rather than relying on opaque or expensive proprietary judge APIs.",
  },
  {
    title: "Inference-First & Lightweight Adaptation",
    description:
      "Investigating post-hoc calibration, test-time reasoning checks, and lightweight parameter-efficient tuning rather than massive compute-heavy re-training.",
  },
];

export const researchCurrentStatus = {
  phase: "Topic Discovery & Literature Review",
  description:
    "Currently conducting structured literature mapping across vision-language hallucination mitigation, designing evaluation protocols for corrupted inputs, and formalizing the final-year undergraduate thesis proposal. No peer-reviewed publications are claimed at this stage.",
};

export const researchAreas: ResearchArea[] = [
  {
    id: "evidence-grounded-reasoning",
    title: "Evidence-Grounded Visual Reasoning & Faithfulness",
    status: "Active Literature Review",
    summary:
      "Investigating mechanisms to enforce that text assertions generated by multimodal models are strictly grounded in verifiable visual features rather than parametric language priors.",
    focusTopics: [
      "Cross-modal attention alignment and attribution analysis",
      "Fine-grained spatial grounding verification",
      "Language prior dominance and ungrounded object hallucination",
      "Contrastive decoding strategies for visual token fidelity",
    ],
    notes:
      "Targeting measurable correlation between visual token attention and factual claims in generated descriptions.",
    methodology: [
      "Benchmarking against standard visual hallucination suites (POPE, MME)",
      "Probing token-level cross-attention during autoregressive generation",
    ],
  },
  {
    id: "calibration-and-abstention",
    title: "Calibration, Uncertainty & Selective Abstention",
    status: "Evaluation Protocol Planning",
    summary:
      "Developing confidence calibration methods that enable vision-language models to reliably withhold answers when visual evidence is insufficient or ambiguous.",
    focusTopics: [
      "Predictive uncertainty quantification under ambiguous visual prompts",
      "Selective abstention thresholding without external verifiers",
      "Calibrated answer confidence in high-stakes reasoning scenarios",
      "Cost-sensitive evaluation metrics penalizing confident errors over abstention",
    ],
    notes:
      "An ungrounded confident prediction is significantly more dangerous than an explicit, calibrated refusal to answer.",
    methodology: [
      "Evaluating risk-coverage trade-offs on ambiguous visual QA queries",
      "Implementing entropy and mutual information-based uncertainty metrics",
    ],
  },
  {
    id: "visual-degradation-robustness",
    title: "Generalization & Robustness Under Degraded Evidence",
    status: "Benchmark Design",
    summary:
      "Assessing how generative MLLMs degrade when images suffer from low resolution, compression artifacts, partial occlusions, or adversarial corruptions.",
    focusTopics: [
      "Performance cliffs under synthetic image corruptions (blur, noise, crop)",
      "Vulnerability to deceptive visual prompts and out-of-distribution artifacts",
      "Robustness disparities between language encoders and vision backbones",
      "Zero-shot recovery methods via test-time visual augmentation",
    ],
    notes:
      "Ensuring that reliability contracts remain predictable across edge capture conditions and real-world sensor limitations.",
    methodology: [
      "Simulating common image corruption distributions across benchmark suites",
      "Analyzing degradation curves of multimodal representations under stress",
    ],
  },
];
